### ISSUE TITLE
Compilation error on Emacs 27

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/ement.el#272]
As reported by @phil-s:

> 
> ​I attempted to test in Emacs 27 and found that ement-room-list doesn't byte-compile. The error is "ement-room-list.el:68:1:Error: Unknown cl-type pattern: (cl-type taxy-magit-section)", coming from the (cl-defmethod magit-section-ident-value ...) definition. I see the same installing in a fresh config. I don't know how to debug that, but potentially it's fixable for 0.15? 
> 
> I can reproduce that by installing Ement 0.14 in 27.2. It does compile in 28.2. [edited] 
>

**Comment by alphapapa** [comment]
I think that should fix it.  Thank you.
